export { default as Investigaciones } from "./Investigaciones/Investigaciones"
export { default as Instrucciones } from "./Instrucciones/Instrucciones"
export { default as About } from "../pages/About/About"
export { default as Mision } from "./Mision/Mision"
export { default as Actual } from "./Actual/Actual"
export { default as Pdf } from "./Pdf/Pdf"
export { default as PageActual } from "./PageActual/PageActual"